# Generated by Django 5.1.5 on 2026-04-27 18:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='Key Name')),
                ('scope', models.CharField(choices=[('kesco_meter_write', 'KESCO meter write')], max_length=50, verbose_name='Scope')),
                ('key_prefix', models.CharField(db_index=True, max_length=16, verbose_name='Key Prefix')),
                ('key_hash', models.CharField(max_length=64, unique=True, verbose_name='Key Hash')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Used At')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User API Key',
                'verbose_name_plural': 'User API Keys',
                'ordering': ['user__username', 'name'],
            },
        ),
    ]
