# Generated by Django 5.1.5 on 2026-04-27 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userapikey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapikey',
            name='scope',
            field=models.CharField(choices=[('kesco_meter_write', 'KESCO meter write'), ('lease_report_read', 'Lease report read')], max_length=50, verbose_name='Scope'),
        ),
    ]
