# Generated by Django 5.1.5 on 2026-04-24 23:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='Location Name')),
                ('address', models.TextField(verbose_name='Location Address')),
                ('google_pin', models.URLField(blank=True, max_length=500, null=True, verbose_name='Google Pin')),
                ('focal_point', models.CharField(blank=True, max_length=255, null=True, verbose_name='Focal Point')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'ordering': ['name'],
            },
        ),
    ]
