# Generated by Django 5.1.5 on 2026-04-25 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='status',
            field=models.CharField(choices=[('vacant', 'Vacant'), ('leased', 'Leased')], default='vacant', max_length=10, verbose_name='Status'),
        ),
    ]
