# Generated by Django 5.1.5 on 2026-04-25 00:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_unit_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='Meter Name')),
                ('meter_type', models.CharField(choices=[('electric', 'Electric'), ('water', 'Water'), ('gas', 'Gas')], max_length=20, verbose_name='Meter Type')),
                ('reading_metric', models.CharField(choices=[('kWh', 'kWh'), ('m³', 'm³'), ('m³_gas', 'm³ (gas)')], max_length=20, verbose_name='Reading Metric')),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Serial Number')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meters', to='locations.unit', verbose_name='Unit')),
            ],
            options={
                'verbose_name': 'Meter',
                'verbose_name_plural': 'Meters',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MeterLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('month', models.IntegerField(verbose_name='Month')),
                ('year', models.IntegerField(verbose_name='Year')),
                ('reading', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Reading')),
                ('billed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Billed Amount (€)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledgers', to='locations.meter', verbose_name='Meter')),
            ],
            options={
                'verbose_name': 'Meter Ledger',
                'verbose_name_plural': 'Meter Ledgers',
                'ordering': ['-year', '-month'],
                'unique_together': {('meter', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='ParkingPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('label', models.CharField(max_length=100, verbose_name='Label')),
                ('covered', models.BooleanField(default=False, verbose_name='Covered')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_places', to='locations.location', verbose_name='Location')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parking_assignments', to='locations.unit', verbose_name='Assigned Unit')),
            ],
            options={
                'verbose_name': 'Parking Place',
                'verbose_name_plural': 'Parking Places',
                'ordering': ['label'],
                'unique_together': {('location', 'label')},
            },
        ),
    ]
