# Generated by Django 5.1.5 on 2026-04-25 00:55

import locations.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_meter_meterledger_parkingplace'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='status',
        ),
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='Responsible Party')),
                ('contact', models.CharField(blank=True, max_length=255, null=True, verbose_name='Contact Person')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('contract', models.FileField(blank=True, null=True, upload_to=locations.models.contract_upload_path, verbose_name='Contract')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('units', models.ManyToManyField(related_name='leases', to='locations.unit', verbose_name='Units')),
            ],
            options={
                'verbose_name': 'Lease',
                'verbose_name_plural': 'Leases',
                'ordering': ['-created_at'],
            },
        ),
    ]
