# Generated by Django 5.1.5 on 2026-04-25 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_remove_unit_status_lease'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lease',
            name='units',
        ),
        migrations.AddField(
            model_name='lease',
            name='advance_months',
            field=models.IntegerField(default=1, verbose_name='Months in Advance'),
        ),
        migrations.AddField(
            model_name='lease',
            name='deposit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Deposit (€)'),
        ),
        migrations.AddField(
            model_name='lease',
            name='monthly_payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monthly Payment (€)'),
        ),
        migrations.AddField(
            model_name='unit',
            name='lease',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_units', to='locations.lease', verbose_name='Lease'),
        ),
    ]
