# Generated by Django 5.1.5 on 2026-04-25 01:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_remove_lease_units_lease_advance_months_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='display_id',
            field=models.CharField(db_index=True, default='', editable=False, max_length=8, unique=True, verbose_name='Lease ID'),
        ),
        migrations.CreateModel(
            name='LeaseLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('month', models.IntegerField(verbose_name='Month')),
                ('year', models.IntegerField(verbose_name='Year')),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount Due (€)')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Amount Paid (€)')),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('partial', 'Partial'), ('unpaid', 'Unpaid'), ('overdue', 'Overdue')], default='unpaid', max_length=10, verbose_name='Status')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Payment Date')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_ledgers', to='locations.lease', verbose_name='Lease')),
            ],
            options={
                'verbose_name': 'Lease Ledger',
                'verbose_name_plural': 'Lease Ledgers',
                'ordering': ['-year', '-month'],
                'unique_together': {('lease', 'month', 'year')},
            },
        ),
    ]
