# Generated by Django 5.1.5 on 2026-04-25 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0007_lease_display_id_leaseledger'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaseledger',
            name='payment_slip',
            field=models.ImageField(blank=True, null=True, upload_to='payment_slips', verbose_name='Payment Slip'),
        ),
    ]
