# Generated by Django 5.1.5 on 2026-04-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0008_leaseledger_payment_slip'),
    ]

    operations = [
        migrations.AddField(
            model_name='meterledger',
            name='settled_at',
            field=models.DateField(blank=True, null=True, verbose_name='Settled Date'),
        ),
    ]
