# Generated by Django 5.1.5 on 2026-04-25 17:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0009_meterledger_settled_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='KescoCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('username', models.CharField(max_length=255, unique=True, verbose_name='KESCO Username / Account ID')),
                ('password', models.CharField(max_length=500, verbose_name='KESCO Password')),
                ('user_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='KESCO User ID')),
                ('bearer_token', models.TextField(blank=True, null=True, verbose_name='Bearer Token')),
                ('token_obtained_at', models.DateTimeField(blank=True, null=True, verbose_name='Token Obtained At')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Token Expires At')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Sync At')),
                ('last_sync_status', models.CharField(blank=True, max_length=50, null=True, verbose_name='Last Sync Status')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'KESCO Credential',
                'verbose_name_plural': 'KESCO Credentials',
                'ordering': ['username'],
            },
        ),
    ]
