# Generated by Django 5.1.5 on 2026-04-25 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0010_kescocredential'),
    ]

    operations = [
        migrations.AddField(
            model_name='meter',
            name='kesco_debitor_id',
            field=models.CharField(blank=True, help_text='Link to KESCO ElDebitorId for automatic sync', max_length=100, null=True, verbose_name='KESCO Debitor ID'),
        ),
    ]
