# Generated by Django 5.1.5 on 2026-04-25 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0011_meter_kesco_debitor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='meter',
            name='kesco_address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='KESCO Consumer Address'),
        ),
        migrations.AddField(
            model_name='meter',
            name='kesco_agency_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='KESCO Agency ID'),
        ),
        migrations.AddField(
            model_name='meter',
            name='kesco_full_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='KESCO Consumer Name'),
        ),
        migrations.AddField(
            model_name='meter',
            name='kesco_last_due_date',
            field=models.DateField(blank=True, null=True, verbose_name='KESCO Last Due Date'),
        ),
        migrations.AddField(
            model_name='meter',
            name='kesco_tariff_group',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='KESCO Tariff Group'),
        ),
    ]
