# Generated by Django 5.1.5 on 2026-04-29 10:52

import django.db.models.deletion
import locations.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0012_meter_kesco_address_meter_kesco_agency_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='buyer_contact',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Buyer Contact Person'),
        ),
        migrations.AddField(
            model_name='unit',
            name='buyer_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Buyer Email'),
        ),
        migrations.AddField(
            model_name='unit',
            name='buyer_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Buyer Name'),
        ),
        migrations.AddField(
            model_name='unit',
            name='buyer_phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Buyer Phone'),
        ),
        migrations.AddField(
            model_name='unit',
            name='sale_agreement_date',
            field=models.DateField(blank=True, null=True, verbose_name='Sale Agreement Date'),
        ),
        migrations.AddField(
            model_name='unit',
            name='sale_contract',
            field=models.FileField(blank=True, null=True, upload_to=locations.models.sale_contract_upload_path, verbose_name='Sale Contract'),
        ),
        migrations.AddField(
            model_name='unit',
            name='sale_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Sale Notes'),
        ),
        migrations.AddField(
            model_name='unit',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Sale Price (€)'),
        ),
        migrations.AddField(
            model_name='unit',
            name='sale_status',
            field=models.CharField(choices=[('not_for_sale', 'Not For Sale'), ('for_sale', 'For Sale'), ('reserved', 'Reserved'), ('sold_partial', 'Sold (Partial)'), ('sold_paid', 'Sold (Paid)'), ('cancelled', 'Cancelled')], default='not_for_sale', max_length=20, verbose_name='Sale Status'),
        ),
        migrations.CreateModel(
            name='SalePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('installment_number', models.IntegerField(verbose_name='Installment #')),
                ('due_date', models.DateField(verbose_name='Due Date')),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount Due (€)')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Amount Paid (€)')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Payment Date')),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partial'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='unpaid', max_length=10, verbose_name='Status')),
                ('payment_slip', models.ImageField(blank=True, null=True, upload_to='sale_payment_slips', verbose_name='Payment Slip')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_payments', to='locations.unit', verbose_name='Unit')),
            ],
            options={
                'verbose_name': 'Sale Payment',
                'verbose_name_plural': 'Sale Payments',
                'ordering': ['unit', 'due_date'],
                'unique_together': {('unit', 'installment_number')},
            },
        ),
    ]
