# Generated by Django 5.1.5 on 2026-04-29 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0013_unit_buyer_contact_unit_buyer_email_unit_buyer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='installment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional — amount for each installment', max_digits=12, null=True, verbose_name='Amount per Installment (€)'),
        ),
        migrations.AddField(
            model_name='unit',
            name='installment_count',
            field=models.IntegerField(blank=True, help_text='Total number of payment installments', null=True, verbose_name='Number of Installments'),
        ),
        migrations.AddField(
            model_name='unit',
            name='installment_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Installment Start Date'),
        ),
    ]
